### ISSUE TITLE
Create support for errors lacking source-attribute

### ISSUE THREAD

**Issue by mnsc** [pellehenriksson/elmah-loganalyzer#6]
Some errors from an asp.net application make Elmah create xml files that lacks the source-attribute on the error-element. How/why I don't know but there have been several examples from our production environment.

Example below, a folder with  two error files where one is missing the attribute.

The file without source don't show up in the left tree (1) som it can't be selected/view. But the two types from the file displays correctly in (2). And (3) confirmes that only one source has been found.

![image](https://cloud.githubusercontent.com/assets/5869639/22775045/309a8498-eeaa-11e6-8f43-494e76bbe1c9.png)

**Comment by pellehenriksson** [comment]
Hi, fixed this issue, if source is missing or if it's value is empty [Unknown-Source] will be used as a default value. https://github.com/pellehenriksson/elmah-loganalyzer/releases
